Array conversion functions
Kotlin/kotlinx-browser pull request #10
Opened 2024-09-24 13:57 UTC by skuzmich

- **Fix issues with :generator:generateWasmStdlibFromIDL task**
- **Add extension methods for primitive JS array conversion**

2024-09-24 14:35 UTC, igoriakovlev requested changes

2024-09-24 14:35 UTC, igoriakovlev commented on src/wasmJsTest/kotlin/arrayCopyTest.kt
> +// See github.com/kotlin/dukat for details
This is not correct, right?

2024-09-24 14:35 UTC, igoriakovlev commented on generator/src/main/kotlin/helpers/generate.kt
> + * Copyright 2010-2020 JetBrains s.r.o. and Kotlin Programming Language contributors.
Should be 2024?

2024-09-24 14:35 UTC, igoriakovlev commented on src/wasmJsMain/kotlin/arrayCopy.kt
> +// See github.com/kotlin/dukat for details
Not correct comment?

2024-09-25 16:02 UTC, skuzmich commented on src/wasmJsTest/kotlin/arrayCopyTest.kt
> +// See github.com/kotlin/dukat for details
Fixed

2024-09-25 16:02 UTC, skuzmich commented on generator/src/main/kotlin/helpers/generate.kt
> + * Copyright 2010-2020 JetBrains s.r.o. and Kotlin Programming Language contributors.
Yes

2024-09-25 16:02 UTC, skuzmich commented on src/wasmJsMain/kotlin/arrayCopy.kt
> +// See github.com/kotlin/dukat for details
Yes, fixed

2024-09-25 16:10 UTC, igoriakovlev commented
Please sqash

2024-09-25 16:22 UTC, merged